# Generated by Django 6.0.2 on 2026-02-19 08:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('registration_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('usage_type', models.CharField(choices=[('office', 'Office'), ('laboratory', 'Laboratory'), ('warehouse', 'Warehouse')], max_length=20)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDirectorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('socket_code', models.CharField(help_text='Unique identifier for the socket.', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='AllInOneComputer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('cpu', models.CharField(max_length=100)),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('screen_size', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='DesktopComputer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('cpu', models.CharField(max_length=100)),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='LaptopComputer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('cpu', models.CharField(max_length=100)),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('screen_size', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('phone_type', models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('printer_type', models.CharField(choices=[('laser', 'Laser'), ('inkjet', 'Inkjet'), ('multifunction', 'Multifunction')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='ServerComputer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('rack_unit', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('layer_capability', models.CharField(choices=[('L2', 'Layer 2'), ('L3', 'Layer 3'), ('L2+L3', 'Layer 2 + Layer 3')], default='L2', max_length=10)),
                ('total_ports', models.IntegerField()),
                ('poe_supported', models.BooleanField(default=False)),
                ('poe_budget_watts', models.IntegerField(blank=True, null=True)),
                ('uplink_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('downlink_speed', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
                ('capacity_va', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UPS',
                'verbose_name_plural': 'UPS units',
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings', to='inventory.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='inventory.city'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departments', to='inventory.directorate')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(-2)])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='floors', to='inventory.building')),
            ],
        ),
        migrations.AddField(
            model_name='directorate',
            name='general_directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='directorates', to='inventory.generaldirectorate'),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offices', to='inventory.department')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('peripheral_type', models.CharField(choices=[('keyboard', 'Keyboard'), ('monitor', 'Monitor'), ('mouse', 'Mouse')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='inventory.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('room_code', models.CharField(max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='inventory.floor')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='socket',
            field=models.ForeignKey(blank=True, help_text='Socket this device is plugged into (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.socket'),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('position_index', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='spaces', to='inventory.room')),
            ],
            options={
                'ordering': ['position_index'],
            },
        ),
        migrations.AddField(
            model_name='socket',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sockets', to='inventory.space'),
        ),
        migrations.AddField(
            model_name='device',
            name='space',
            field=models.ForeignKey(help_text='Space where this device is located', on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='inventory.space'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.department')),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.directorate')),
                ('general_directorate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.generaldirectorate')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('shared', 'Shared'), ('temporary', 'Temporary')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_area_per_city'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('directorate', 'name'), name='unique_department_per_directorate'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'floor_number')},
        ),
        migrations.AddConstraint(
            model_name='directorate',
            constraint=models.UniqueConstraint(fields=('general_directorate', 'name'), name='unique_directorate_per_gd'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_office_per_department'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'room_code')},
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('room', 'name'), ('room', 'position_index')},
        ),
    ]
