# Generated by Django 6.0.2 on 2026-02-20 07:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('room', 'position_index')},
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.CheckConstraint(condition=models.Q(('floor_number__gte', -2)), name='floor_number_min_minus_2', violation_error_message='Ο αριθμός ορόφου δεν μπορεί να είναι μικρότερος του -2.'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('room'), name='unique_space_name_per_room_ci'),
        ),
    ]
