# Generated by Django 6.0.2 on 2026-02-20 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_space_unique_together_alter_floor_floor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='space',
            field=models.ForeignKey(blank=True, help_text='Space where this device is located (για κανονικά γραφεία/δωμάτια)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='inventory.space'),
        ),
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('area_type', models.CharField(choices=[('corridor', 'Corridor'), ('lobby', 'Lobby'), ('staircase', 'Staircase'), ('wc', 'WC'), ('kitchen', 'Kitchen'), ('server_room', 'Server Room'), ('other', 'Other')], default='corridor', max_length=20)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='common_areas', to='inventory.floor')),
            ],
            options={
                'unique_together': {('floor', 'name')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='common_area',
            field=models.ForeignKey(blank=True, help_text='Common area where this device is located (για διαδρόμους/κοινόχρηστους χώρους)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='inventory.commonarea'),
        ),
    ]
